disabled_rules:
   - trailing_whitespace
   - unused_closure_parameter
   - closure_parameter_position
   - identifier_name
   - fallthrough
   - no_fallthrough_only
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Source/UI/Capture/Code Icons
  - Source/UI/Capture/Permissions/Code Icons
  - Resources/Images/Vector Images
identifier_name:
  min_length:
    warning: 2
    error: 2
type_name:
    min_length: 2
    max_length:
        warning: 45
        error: 50
line_length:
  warning: 120
large_tuple:
  warning: 3
  error: 5
type_body_length: 300
nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 6
